//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/InputActions/CraneInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @CraneInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CraneInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CraneInputActions"",
    ""maps"": [
        {
            ""name"": ""CraneMovement"",
            ""id"": ""619406dd-a5af-4a02-921a-e1768cf6cb5a"",
            ""actions"": [
                {
                    ""name"": ""Grab"",
                    ""type"": ""Button"",
                    ""id"": ""5ea2947d-d2e3-44b7-9567-612778018a51"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Throw"",
                    ""type"": ""Button"",
                    ""id"": ""b90b5454-0f83-470f-b01e-afa0ccd4a2a6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Start"",
                    ""type"": ""Button"",
                    ""id"": ""fd16936d-2c93-4496-9f45-4187e48264a8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Boost"",
                    ""type"": ""Button"",
                    ""id"": ""be98b64c-ecd8-4427-ba58-6c2c73bd7c56"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""bd7ec791-dc1f-45c3-9584-7124accc588b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""87ce558f-b56c-4aca-86cd-5c290e38b558"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""204f80ad-a773-4759-8200-472450009ac5"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f17c98f-b200-4459-960a-842565a82e4f"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dacee5d6-8b99-422b-aea6-5bcbd6c40672"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Boost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c968ff2e-58d0-46e9-b82e-c6be62c6d377"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // CraneMovement
        m_CraneMovement = asset.FindActionMap("CraneMovement", throwIfNotFound: true);
        m_CraneMovement_Grab = m_CraneMovement.FindAction("Grab", throwIfNotFound: true);
        m_CraneMovement_Throw = m_CraneMovement.FindAction("Throw", throwIfNotFound: true);
        m_CraneMovement_Start = m_CraneMovement.FindAction("Start", throwIfNotFound: true);
        m_CraneMovement_Boost = m_CraneMovement.FindAction("Boost", throwIfNotFound: true);
        m_CraneMovement_Shoot = m_CraneMovement.FindAction("Shoot", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CraneMovement
    private readonly InputActionMap m_CraneMovement;
    private List<ICraneMovementActions> m_CraneMovementActionsCallbackInterfaces = new List<ICraneMovementActions>();
    private readonly InputAction m_CraneMovement_Grab;
    private readonly InputAction m_CraneMovement_Throw;
    private readonly InputAction m_CraneMovement_Start;
    private readonly InputAction m_CraneMovement_Boost;
    private readonly InputAction m_CraneMovement_Shoot;
    public struct CraneMovementActions
    {
        private @CraneInputActions m_Wrapper;
        public CraneMovementActions(@CraneInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Grab => m_Wrapper.m_CraneMovement_Grab;
        public InputAction @Throw => m_Wrapper.m_CraneMovement_Throw;
        public InputAction @Start => m_Wrapper.m_CraneMovement_Start;
        public InputAction @Boost => m_Wrapper.m_CraneMovement_Boost;
        public InputAction @Shoot => m_Wrapper.m_CraneMovement_Shoot;
        public InputActionMap Get() { return m_Wrapper.m_CraneMovement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CraneMovementActions set) { return set.Get(); }
        public void AddCallbacks(ICraneMovementActions instance)
        {
            if (instance == null || m_Wrapper.m_CraneMovementActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CraneMovementActionsCallbackInterfaces.Add(instance);
            @Grab.started += instance.OnGrab;
            @Grab.performed += instance.OnGrab;
            @Grab.canceled += instance.OnGrab;
            @Throw.started += instance.OnThrow;
            @Throw.performed += instance.OnThrow;
            @Throw.canceled += instance.OnThrow;
            @Start.started += instance.OnStart;
            @Start.performed += instance.OnStart;
            @Start.canceled += instance.OnStart;
            @Boost.started += instance.OnBoost;
            @Boost.performed += instance.OnBoost;
            @Boost.canceled += instance.OnBoost;
            @Shoot.started += instance.OnShoot;
            @Shoot.performed += instance.OnShoot;
            @Shoot.canceled += instance.OnShoot;
        }

        private void UnregisterCallbacks(ICraneMovementActions instance)
        {
            @Grab.started -= instance.OnGrab;
            @Grab.performed -= instance.OnGrab;
            @Grab.canceled -= instance.OnGrab;
            @Throw.started -= instance.OnThrow;
            @Throw.performed -= instance.OnThrow;
            @Throw.canceled -= instance.OnThrow;
            @Start.started -= instance.OnStart;
            @Start.performed -= instance.OnStart;
            @Start.canceled -= instance.OnStart;
            @Boost.started -= instance.OnBoost;
            @Boost.performed -= instance.OnBoost;
            @Boost.canceled -= instance.OnBoost;
            @Shoot.started -= instance.OnShoot;
            @Shoot.performed -= instance.OnShoot;
            @Shoot.canceled -= instance.OnShoot;
        }

        public void RemoveCallbacks(ICraneMovementActions instance)
        {
            if (m_Wrapper.m_CraneMovementActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICraneMovementActions instance)
        {
            foreach (var item in m_Wrapper.m_CraneMovementActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CraneMovementActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CraneMovementActions @CraneMovement => new CraneMovementActions(this);
    public interface ICraneMovementActions
    {
        void OnGrab(InputAction.CallbackContext context);
        void OnThrow(InputAction.CallbackContext context);
        void OnStart(InputAction.CallbackContext context);
        void OnBoost(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
    }
}
